// Generates lib/features/account/legal_data.g.dart from the policy text shared with the website.
// Run from apps/customer:  dart run tool/gen_legal.dart
import 'dart:convert';
import 'dart:io';

const _source = '../../packages/legal/legal.json';
const _target = 'lib/features/account/legal_data.g.dart';

/// A Dart single-quoted string literal for [s].
String _q(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$').replaceAll('\n', r'\n')}'";

String _list(List<dynamic> items, String indent) => items.isEmpty ? '' : '[\n${items.map((e) => '$indent  ${_q(e as String)},\n').join()}$indent]';

void main() {
  final data = jsonDecode(File(_source).readAsStringSync()) as Map<String, dynamic>;
  final docs = data['documents'] as Map<String, dynamic>;
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_legal.dart from packages/legal/legal.json. Do not edit.')
    ..writeln()
    ..writeln("import 'legal_content.dart';")
    ..writeln()
    ..writeln('const legalCompany = ${_q(data['company'] as String)};')
    ..writeln('const legalUpdated = ${_q(data['updated'] as String)};');

  for (final MapEntry(:key, :value) in docs.entries) {
    final doc = value as Map<String, dynamic>;
    final name = 'legal${key[0].toUpperCase()}${key.substring(1)}';
    out
      ..writeln()
      ..writeln('const $name = LegalPage(')
      ..writeln('  title: ${_q(doc['title'] as String)},')
      ..writeln('  sections: [');
    for (final s in doc['sections'] as List<dynamic>) {
      final section = s as Map<String, dynamic>;
      final paragraphs = _list((section['paragraphs'] as List<dynamic>?) ?? const [], '      ');
      final bullets = _list((section['bullets'] as List<dynamic>?) ?? const [], '      ');
      out.writeln('    LegalSection(');
      out.writeln('      ${_q(section['heading'] as String)},');
      if (paragraphs.isNotEmpty) out.writeln('      paragraphs: $paragraphs,');
      if (bullets.isNotEmpty) out.writeln('      bullets: $bullets,');
      out.writeln('    ),');
    }
    out
      ..writeln('  ],')
      ..writeln(');');
  }

  File(_target).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_target');
}
