// Generates lib/design/tokens.g.dart from the shared design tokens.
// Run from apps/customer:  dart run tool/gen_tokens.dart
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

const _source = '../../packages/design-tokens/tokens.json';
const _target = 'lib/design/tokens.g.dart';

void main() {
  final tokens = jsonDecode(File(_source).readAsStringSync()) as Map<String, dynamic>;
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tokens.dart from packages/design-tokens/tokens.json. Do not edit.')
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln();

  _colors(out, tokens['color'] as Map<String, dynamic>);
  _shadows(out, tokens['shadow'] as Map<String, dynamic>);
  _scale(out, 'IdSpace', 'Spacing scale (dp).', tokens['spacing'], (n) => n.replaceFirst('space-', 's'));
  _scale(out, 'IdRadius', 'Corner radii (dp).', tokens['radius'], (n) => n.replaceFirst('radius-', ''));
  _scale(out, 'IdSize', 'Fixed component sizes (dp).', tokens['size'], (n) => n);
  _type(out, tokens['type'] as Map<String, dynamic>);

  File(_target).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_target');
}

// ── Colours ────────────────────────────────────────────────────────────────

void _colors(StringBuffer out, Map<String, dynamic> color) {
  final themes = [for (final t in color['themes'] as List) (t as Map)['id'] as String];
  final list = (color['tokens'] as List).cast<Map<String, dynamic>>();
  final byName = {for (final t in list) t['name'] as String: t};

  String resolve(String name, String theme, [int depth = 0]) {
    if (depth > 16) throw StateError('Alias chain too deep at $name');
    final value = byName[name]!['value'];
    final raw = value is String ? value : ((value as Map)[theme] ?? value[themes.first]) as String;
    final alias = RegExp(r'^\{(.+)\}$').firstMatch(raw);
    return alias == null ? raw : resolve(alias.group(1)!, theme, depth + 1);
  }

  final fields = [for (final t in list) (name: t['name'] as String, id: _camel(t['name'] as String), usage: t['usage'] as String?)];

  out
    ..writeln('/// Theme-aware colours from the design system. Read them with `context.colors`.')
    ..writeln('@immutable')
    ..writeln('class IdColors extends ThemeExtension<IdColors> {')
    ..writeln('  const IdColors({')
    ..writeAll([for (final f in fields) '    required this.${f.id},\n'])
    ..writeln('  });')
    ..writeln();
  for (final f in fields) {
    if (f.usage != null) out.writeln('  /// ${_oneLine(f.usage!)}');
    out.writeln('  final Color ${f.id};');
  }
  for (final theme in themes) {
    out
      ..writeln()
      ..writeln('  static const $theme = IdColors(');
    for (final f in fields) {
      out.writeln('    ${f.id}: ${_color(resolve(f.name, theme))},');
    }
    out.writeln('  );');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln('  IdColors copyWith({${fields.map((f) => 'Color? ${f.id}').join(', ')}}) => IdColors(')
    ..writeAll([for (final f in fields) '        ${f.id}: ${f.id} ?? this.${f.id},\n'])
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  IdColors lerp(IdColors? other, double t) {')
    ..writeln('    if (other == null) return this;')
    ..writeln('    return IdColors(')
    ..writeAll([for (final f in fields) '      ${f.id}: Color.lerp(${f.id}, other.${f.id}, t)!,\n'])
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}')
    ..writeln();
}

String _color(String css) {
  final hex = RegExp(r'^#([0-9a-fA-F]{3,8})$').firstMatch(css);
  if (hex != null) {
    var h = hex.group(1)!;
    if (h.length == 3) h = h.split('').map((c) => '$c$c').join();
    if (h.length == 6) h = 'ff$h';
    if (h.length == 8 && css.length == 9) h = '${h.substring(6)}${h.substring(0, 6)}'; // #rrggbbaa → aarrggbb
    return 'Color(0x${h.toUpperCase()})';
  }
  final rgba = RegExp(r'^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$').firstMatch(css);
  if (rgba != null) {
    final a = rgba.group(4) == null ? 255 : (double.parse(rgba.group(4)!) * 255).round();
    final parts = [a, int.parse(rgba.group(1)!), int.parse(rgba.group(2)!), int.parse(rgba.group(3)!)];
    return 'Color(0x${parts.map((v) => v.toRadixString(16).padLeft(2, '0')).join().toUpperCase()})';
  }
  throw FormatException('Unsupported colour: $css');
}

// ── Shadows ────────────────────────────────────────────────────────────────

void _shadows(StringBuffer out, Map<String, dynamic> shadow) {
  final list = (shadow['tokens'] as List).cast<Map<String, dynamic>>();
  final fields = [for (final t in list) (id: _camel((t['name'] as String).replaceFirst('shadow-', '')), value: t['value'], usage: t['usage'] as String?)];
  const themes = ['light', 'dark'];

  out
    ..writeln('/// Elevation shadows from the design system. Read them with `context.shadows`.')
    ..writeln('@immutable')
    ..writeln('class IdShadows extends ThemeExtension<IdShadows> {')
    ..writeln('  const IdShadows({${fields.map((f) => 'required this.${f.id}').join(', ')}});')
    ..writeln();
  for (final f in fields) {
    if (f.usage != null) out.writeln('  /// ${_oneLine(f.usage!)}');
    out.writeln('  final List<BoxShadow> ${f.id};');
  }
  for (final theme in themes) {
    out
      ..writeln()
      ..writeln('  static const $theme = IdShadows(');
    for (final f in fields) {
      final v = f.value;
      final css = v is String ? v : ((v as Map)[theme] ?? v['light']) as String;
      out.writeln('    ${f.id}: ${_boxShadows(css)},');
    }
    out.writeln('  );');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln('  IdShadows copyWith({${fields.map((f) => 'List<BoxShadow>? ${f.id}').join(', ')}}) =>')
    ..writeln('      IdShadows(${fields.map((f) => '${f.id}: ${f.id} ?? this.${f.id}').join(', ')});')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  IdShadows lerp(IdShadows? other, double t) {')
    ..writeln('    if (other == null) return this;')
    ..writeln('    return IdShadows(')
    ..writeAll([for (final f in fields) '      ${f.id}: BoxShadow.lerpList(${f.id}, other.${f.id}, t) ?? const [],\n'])
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}')
    ..writeln();
}

/// CSS box-shadow list → BoxShadow list. CSS blur B is a Gaussian with sigma B/2;
/// Flutter's blurRadius r maps to sigma r * 0.57735 + 0.5, so r = (B/2 - 0.5) / 0.57735.
String _boxShadows(String css) {
  if (css.trim() == 'none') return '<BoxShadow>[]';
  final shadows = <String>[];
  for (final part in css.split(RegExp(r',(?![^(]*\))'))) {
    final m = RegExp(r'^\s*(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+([\d.]+)(?:px)?\s*(?:([\d.]+)(?:px)?\s+)?(rgba?\([^)]*\)|#[0-9a-fA-F]+)\s*$').firstMatch(part);
    if (m == null) throw FormatException('Unsupported shadow: $part');
    final blur = double.parse(m.group(3)!);
    final radius = math.max(0, (blur / 2 - 0.5) / 0.57735);
    final spread = m.group(4) == null ? '' : ', spreadRadius: ${m.group(4)}';
    shadows.add('BoxShadow(color: ${_color(m.group(5)!)}, offset: Offset(${m.group(1)}, ${m.group(2)}), blurRadius: ${radius.toStringAsFixed(2)}$spread)');
  }
  return '<BoxShadow>[${shadows.join(', ')}]';
}

// ── Scales ─────────────────────────────────────────────────────────────────

void _scale(StringBuffer out, String className, String doc, dynamic family, String Function(String) rename) {
  final list = ((family as Map)['tokens'] as List).cast<Map<String, dynamic>>();
  out
    ..writeln('/// $doc')
    ..writeln('abstract final class $className {');
  for (final t in list) {
    final usage = t['usage'] as String?;
    if (usage != null) out.writeln('  /// ${_oneLine(usage)}');
    out.writeln('  static const double ${_camel(rename(t['name'] as String))} = ${_px(t['value'])};');
  }
  out
    ..writeln('}')
    ..writeln();
}

double _px(Object? v) => v is num ? v.toDouble() : double.parse((v as String).replaceAll('px', ''));

// ── Type ───────────────────────────────────────────────────────────────────

void _type(StringBuffer out, Map<String, dynamic> type) {
  final families = (type['families'] as Map).map((k, v) => MapEntry(k as String, _firstFamily(v as String)));
  out
    ..writeln('/// Font families. The app loads them with google_fonts.')
    ..writeln('abstract final class IdFont {');
  families.forEach((key, family) => out.writeln("  static const $key = '$family';"));
  out
    ..writeln('}')
    ..writeln()
    ..writeln('/// One type style from the design system: family, size, line height, weight and tracking.')
    ..writeln('@immutable')
    ..writeln('class IdTypeSpec {')
    ..writeln('  const IdTypeSpec(this.family, this.size, this.lineHeight, this.weight, this.letterSpacingEm);')
    ..writeln('  final String family;')
    ..writeln('  final double size;')
    ..writeln('  final double lineHeight;')
    ..writeln('  final FontWeight weight;')
    ..writeln('  final double letterSpacingEm;')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Type scale. Use the TextStyles from `context.text` (theme.dart) rather than these directly.')
    ..writeln('abstract final class IdType {');
  for (final group in (type['groups'] as List).cast<Map<String, dynamic>>()) {
    for (final s in (group['styles'] as List).cast<Map<String, dynamic>>()) {
      final familyKey = (s['family'] ?? group['family']) as String;
      final size = _px(s['fontSize']);
      final line = _px(s['lineHeight']);
      final weight = (s['fontWeight'] as num).toInt();
      final tracking = s['letterSpacing'] == null ? 0.0 : double.parse((s['letterSpacing'] as String).replaceAll('em', ''));
      final usage = s['usage'] as String?;
      if (usage != null) out.writeln('  /// ${_oneLine(usage)}');
      out.writeln('  static const ${_camel(s['name'] as String)} = IdTypeSpec(IdFont.$familyKey, $size, $line, FontWeight.w$weight, $tracking);');
    }
  }
  out.writeln('}');
}

String _firstFamily(String stack) => stack.split(',').first.trim().replaceAll('"', '').replaceAll("'", '');

// ── Helpers ────────────────────────────────────────────────────────────────

String _camel(String name) {
  final parts = name.split(RegExp(r'[-_.\s]+')).where((p) => p.isNotEmpty).toList();
  final camel = parts.first + parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  return RegExp(r'^\d').hasMatch(camel) ? 'v$camel' : camel;
}

String _oneLine(String s) => s.replaceAll(RegExp(r'\s+'), ' ').replaceAll('`', '').trim();
