// IronDost brand colours. Generated by packages/brand/scripts/build-svg.py; do not edit by hand.
import 'package:flutter/painting.dart';

abstract final class BrandColors {
  static const ink = Color(0xFF0E1E3D);
  static const royal = Color(0xFF1F4FD1);
  static const sky = Color(0xFF3FB8EA);
  static const ocean = Color(0xFF1A73B0);
  static const sun = Color(0xFFFFC93C);
  static const mist = Color(0xFFE6EEF8);
  static const white = Color(0xFFFFFFFF);
  static const steel = Color(0xFFC9D2DD);
  static const ring = Color(0xFFDCE4EE);
  static const glass = Color(0xFFBFEAF8);
  static const foam = Color(0xFFD9F4FC);
  static const chrome = Color(0xFFF1F4F8);
}
