// GENERATED by tool/gen_tokens.dart from packages/design-tokens/tokens.json. Do not edit.
// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

/// Theme-aware colours from the design system. Read them with `context.colors`.
@immutable
class IdColors extends ThemeExtension<IdColors> {
  const IdColors({
    required this.ink,
    required this.royal,
    required this.sky,
    required this.ocean,
    required this.sun,
    required this.mist,
    required this.white,
    required this.bg,
    required this.surface,
    required this.surfaceSoft,
    required this.surfaceInverse,
    required this.text,
    required this.textMuted,
    required this.textInverse,
    required this.inverseAccent,
    required this.primary,
    required this.primaryPressed,
    required this.onPrimary,
    required this.primarySoft,
    required this.onPrimarySoft,
    required this.accent,
    required this.offer,
    required this.onOffer,
    required this.offerSoft,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.danger,
    required this.dangerSoft,
    required this.border,
    required this.borderStrong,
    required this.focusRing,
    required this.scrim,
    required this.illoSteel,
    required this.illoRing,
    required this.illoGlass,
    required this.illoFoam,
    required this.illoChrome,
  });

  /// Brand ink: the logo's outlines, the word "Iron", dark brand surfaces. For UI text use text, which follows the theme.
  final Color ink;
  /// Brand primary: the word "Dost", the iron's body. UI actions use primary, which is royal in light mode.
  final Color royal;
  /// Water and fills in illustrations; accent text on dark grounds only (2.3:1 on white, never text on light).
  final Color sky;
  /// Sky's text-safe partner on light grounds (5.1:1 on white): the tagline, informational links.
  final Color ocean;
  /// Offers, savings and highlights. Always carries ink text (10.8:1), never white.
  final Color sun;
  /// Soft brand panels and the washer's control panel in illustrations.
  final Color mist;
  /// Washer and iron bodies in illustrations; logo ground.
  final Color white;
  /// App background behind cards, lists and sheets.
  final Color bg;
  /// Cards, sheets, inputs, app bars and the bottom navigation.
  final Color surface;
  /// Grouped panels inside a card, skeleton loaders, unselected chips.
  final Color surfaceSoft;
  /// Snackbars and the dark hero card on order tracking.
  final Color surfaceInverse;
  /// Primary text and icons on bg, surface and surface-soft (light 16:1, dark 15:1).
  final Color text;
  /// Secondary text, captions and inactive icons on bg, surface and surface-soft (light ≥5.9:1, dark ≥6.4:1).
  final Color textMuted;
  /// Text on surface-inverse.
  final Color textInverse;
  /// Action text on surface-inverse, e.g. the snackbar's "Undo" (light 7.3:1, dark 5.8:1).
  final Color inverseAccent;
  /// The one main action per screen, links, selected states, progress. On surface and bg: light 6.8:1, dark 6.5:1.
  final Color primary;
  /// Pressed state of primary fills.
  final Color primaryPressed;
  /// Text and icons on primary fills (light 6.8:1, dark 6.7:1).
  final Color onPrimary;
  /// Selected chips and slots, the active tab indicator, info fills. Pair with on-primary-soft.
  final Color primarySoft;
  /// Text and icons on primary-soft (light 5.8:1, dark 5.2:1).
  final Color onPrimarySoft;
  /// Informational accents: the live-tracking line, "Partner on the way", the out-for-delivery chip. Light is ocean deepened for small text: 6.4:1 on surface, 5.5:1 on surface-soft; dark is sky (7:1, 6:1).
  final Color accent;
  /// Offer badges, promo cards and the "You saved" pill. Pair with on-offer.
  final Color offer;
  /// Text on offer (10.8:1).
  final Color onOffer;
  /// Large promo backgrounds; text on it is text.
  final Color offerSoft;
  /// Delivered, paid, savings amounts. On surface 5.8:1 / 8.6:1; on success-soft 5.1:1 / 6.8:1. Always with an icon or word.
  final Color success;
  /// Background of success chips and banners.
  final Color successSoft;
  /// Unpaid amounts, slots closing soon. On warning-soft 5.3:1 / 8.4:1.
  final Color warning;
  /// Background of warning chips and banners.
  final Color warningSoft;
  /// Errors, cancellation, account deletion. On surface 5.6:1 / 7:1; on danger-soft 4.9:1 / 7.1:1.
  final Color danger;
  /// Background of error banners and the cancelled chip.
  final Color dangerSoft;
  /// Dividers and card outlines (decorative, never the only boundary of a control).
  final Color border;
  /// Input, checkbox and outline-button borders: ≥3:1 on surface and bg in both themes.
  final Color borderStrong;
  /// 2px keyboard and switch-access focus ring, offset 2px; ≥6.5:1 on every surface.
  final Color focusRing;
  /// Behind bottom sheets and dialogs.
  final Color scrim;
  /// Illustration: the iron's soleplate and metal parts.
  final Color illoSteel;
  /// Illustration: the washer door ring.
  final Color illoRing;
  /// Illustration: glass and window highlights.
  final Color illoGlass;
  /// Illustration: soap bubbles and foam.
  final Color illoFoam;
  /// Illustration: chrome highlights.
  final Color illoChrome;

  static const light = IdColors(
    ink: Color(0xFF0E1E3D),
    royal: Color(0xFF1F4FD1),
    sky: Color(0xFF3FB8EA),
    ocean: Color(0xFF1A73B0),
    sun: Color(0xFFFFC93C),
    mist: Color(0xFFE6EEF8),
    white: Color(0xFFFFFFFF),
    bg: Color(0xFFF5F8FC),
    surface: Color(0xFFFFFFFF),
    surfaceSoft: Color(0xFFE6EEF8),
    surfaceInverse: Color(0xFF0E1E3D),
    text: Color(0xFF0E1E3D),
    textMuted: Color(0xFF4A5A77),
    textInverse: Color(0xFFFFFFFF),
    inverseAccent: Color(0xFF3FB8EA),
    primary: Color(0xFF1F4FD1),
    primaryPressed: Color(0xFF1A43B3),
    onPrimary: Color(0xFFFFFFFF),
    primarySoft: Color(0xFFE8EEFC),
    onPrimarySoft: Color(0xFF1F4FD1),
    accent: Color(0xFF16639A),
    offer: Color(0xFFFFC93C),
    onOffer: Color(0xFF0E1E3D),
    offerSoft: Color(0xFFFFF4D1),
    success: Color(0xFF1A7347),
    successSoft: Color(0xFFE3F4EA),
    warning: Color(0xFF8A5A00),
    warningSoft: Color(0xFFFFF1CC),
    danger: Color(0xFFC62828),
    dangerSoft: Color(0xFFFDECEB),
    border: Color(0xFFDCE4EE),
    borderStrong: Color(0xFF7D8BA3),
    focusRing: Color(0xFF1F4FD1),
    scrim: Color(0x800E1E3D),
    illoSteel: Color(0xFFC9D2DD),
    illoRing: Color(0xFFDCE4EE),
    illoGlass: Color(0xFFBFEAF8),
    illoFoam: Color(0xFFD9F4FC),
    illoChrome: Color(0xFFF1F4F8),
  );

  static const dark = IdColors(
    ink: Color(0xFF0E1E3D),
    royal: Color(0xFF1F4FD1),
    sky: Color(0xFF3FB8EA),
    ocean: Color(0xFF1A73B0),
    sun: Color(0xFFFFC93C),
    mist: Color(0xFFE6EEF8),
    white: Color(0xFFFFFFFF),
    bg: Color(0xFF0B1630),
    surface: Color(0xFF12213F),
    surfaceSoft: Color(0xFF1A2C52),
    surfaceInverse: Color(0xFFE6EEF8),
    text: Color(0xFFEEF3FA),
    textMuted: Color(0xFFA9B6CC),
    textInverse: Color(0xFF0E1E3D),
    inverseAccent: Color(0xFF1F4FD1),
    primary: Color(0xFF7FA2FF),
    primaryPressed: Color(0xFF9DB8FF),
    onPrimary: Color(0xFF0E1E3D),
    primarySoft: Color(0xFF1C2F63),
    onPrimarySoft: Color(0xFF7FA2FF),
    accent: Color(0xFF3FB8EA),
    offer: Color(0xFFFFC93C),
    onOffer: Color(0xFF0E1E3D),
    offerSoft: Color(0xFF3A3112),
    success: Color(0xFF5FD39A),
    successSoft: Color(0xFF133A2A),
    warning: Color(0xFFFFC93C),
    warningSoft: Color(0xFF3A3112),
    danger: Color(0xFFFF8A80),
    dangerSoft: Color(0xFF3D1A1D),
    border: Color(0xFF26375A),
    borderStrong: Color(0xFF6F82A6),
    focusRing: Color(0xFF3FB8EA),
    scrim: Color(0x99000000),
    illoSteel: Color(0xFFC9D2DD),
    illoRing: Color(0xFFDCE4EE),
    illoGlass: Color(0xFFBFEAF8),
    illoFoam: Color(0xFFD9F4FC),
    illoChrome: Color(0xFFF1F4F8),
  );

  @override
  IdColors copyWith({Color? ink, Color? royal, Color? sky, Color? ocean, Color? sun, Color? mist, Color? white, Color? bg, Color? surface, Color? surfaceSoft, Color? surfaceInverse, Color? text, Color? textMuted, Color? textInverse, Color? inverseAccent, Color? primary, Color? primaryPressed, Color? onPrimary, Color? primarySoft, Color? onPrimarySoft, Color? accent, Color? offer, Color? onOffer, Color? offerSoft, Color? success, Color? successSoft, Color? warning, Color? warningSoft, Color? danger, Color? dangerSoft, Color? border, Color? borderStrong, Color? focusRing, Color? scrim, Color? illoSteel, Color? illoRing, Color? illoGlass, Color? illoFoam, Color? illoChrome}) => IdColors(
        ink: ink ?? this.ink,
        royal: royal ?? this.royal,
        sky: sky ?? this.sky,
        ocean: ocean ?? this.ocean,
        sun: sun ?? this.sun,
        mist: mist ?? this.mist,
        white: white ?? this.white,
        bg: bg ?? this.bg,
        surface: surface ?? this.surface,
        surfaceSoft: surfaceSoft ?? this.surfaceSoft,
        surfaceInverse: surfaceInverse ?? this.surfaceInverse,
        text: text ?? this.text,
        textMuted: textMuted ?? this.textMuted,
        textInverse: textInverse ?? this.textInverse,
        inverseAccent: inverseAccent ?? this.inverseAccent,
        primary: primary ?? this.primary,
        primaryPressed: primaryPressed ?? this.primaryPressed,
        onPrimary: onPrimary ?? this.onPrimary,
        primarySoft: primarySoft ?? this.primarySoft,
        onPrimarySoft: onPrimarySoft ?? this.onPrimarySoft,
        accent: accent ?? this.accent,
        offer: offer ?? this.offer,
        onOffer: onOffer ?? this.onOffer,
        offerSoft: offerSoft ?? this.offerSoft,
        success: success ?? this.success,
        successSoft: successSoft ?? this.successSoft,
        warning: warning ?? this.warning,
        warningSoft: warningSoft ?? this.warningSoft,
        danger: danger ?? this.danger,
        dangerSoft: dangerSoft ?? this.dangerSoft,
        border: border ?? this.border,
        borderStrong: borderStrong ?? this.borderStrong,
        focusRing: focusRing ?? this.focusRing,
        scrim: scrim ?? this.scrim,
        illoSteel: illoSteel ?? this.illoSteel,
        illoRing: illoRing ?? this.illoRing,
        illoGlass: illoGlass ?? this.illoGlass,
        illoFoam: illoFoam ?? this.illoFoam,
        illoChrome: illoChrome ?? this.illoChrome,
      );

  @override
  IdColors lerp(IdColors? other, double t) {
    if (other == null) return this;
    return IdColors(
      ink: Color.lerp(ink, other.ink, t)!,
      royal: Color.lerp(royal, other.royal, t)!,
      sky: Color.lerp(sky, other.sky, t)!,
      ocean: Color.lerp(ocean, other.ocean, t)!,
      sun: Color.lerp(sun, other.sun, t)!,
      mist: Color.lerp(mist, other.mist, t)!,
      white: Color.lerp(white, other.white, t)!,
      bg: Color.lerp(bg, other.bg, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surfaceSoft: Color.lerp(surfaceSoft, other.surfaceSoft, t)!,
      surfaceInverse: Color.lerp(surfaceInverse, other.surfaceInverse, t)!,
      text: Color.lerp(text, other.text, t)!,
      textMuted: Color.lerp(textMuted, other.textMuted, t)!,
      textInverse: Color.lerp(textInverse, other.textInverse, t)!,
      inverseAccent: Color.lerp(inverseAccent, other.inverseAccent, t)!,
      primary: Color.lerp(primary, other.primary, t)!,
      primaryPressed: Color.lerp(primaryPressed, other.primaryPressed, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      primarySoft: Color.lerp(primarySoft, other.primarySoft, t)!,
      onPrimarySoft: Color.lerp(onPrimarySoft, other.onPrimarySoft, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      offer: Color.lerp(offer, other.offer, t)!,
      onOffer: Color.lerp(onOffer, other.onOffer, t)!,
      offerSoft: Color.lerp(offerSoft, other.offerSoft, t)!,
      success: Color.lerp(success, other.success, t)!,
      successSoft: Color.lerp(successSoft, other.successSoft, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningSoft: Color.lerp(warningSoft, other.warningSoft, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      dangerSoft: Color.lerp(dangerSoft, other.dangerSoft, t)!,
      border: Color.lerp(border, other.border, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
      focusRing: Color.lerp(focusRing, other.focusRing, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
      illoSteel: Color.lerp(illoSteel, other.illoSteel, t)!,
      illoRing: Color.lerp(illoRing, other.illoRing, t)!,
      illoGlass: Color.lerp(illoGlass, other.illoGlass, t)!,
      illoFoam: Color.lerp(illoFoam, other.illoFoam, t)!,
      illoChrome: Color.lerp(illoChrome, other.illoChrome, t)!,
    );
  }
}

/// Elevation shadows from the design system. Read them with `context.shadows`.
@immutable
class IdShadows extends ThemeExtension<IdShadows> {
  const IdShadows({required this.card, required this.raised, required this.sheet});

  /// Cards on bg.
  final List<BoxShadow> card;
  /// Floating elements: the cart bar, menus, snackbars.
  final List<BoxShadow> raised;
  /// Bottom sheets and sticky bottom action bars.
  final List<BoxShadow> sheet;

  static const light = IdShadows(
    card: <BoxShadow>[BoxShadow(color: Color(0x0F0E1E3D), offset: Offset(0, 1), blurRadius: 0.87), BoxShadow(color: Color(0x0F0E1E3D), offset: Offset(0, 2), blurRadius: 6.06)],
    raised: <BoxShadow>[BoxShadow(color: Color(0x1F0E1E3D), offset: Offset(0, 6), blurRadius: 16.45)],
    sheet: <BoxShadow>[BoxShadow(color: Color(0x240E1E3D), offset: Offset(0, -6), blurRadius: 19.92)],
  );

  static const dark = IdShadows(
    card: <BoxShadow>[],
    raised: <BoxShadow>[BoxShadow(color: Color(0x80000000), offset: Offset(0, 6), blurRadius: 16.45)],
    sheet: <BoxShadow>[BoxShadow(color: Color(0x99000000), offset: Offset(0, -6), blurRadius: 19.92)],
  );

  @override
  IdShadows copyWith({List<BoxShadow>? card, List<BoxShadow>? raised, List<BoxShadow>? sheet}) =>
      IdShadows(card: card ?? this.card, raised: raised ?? this.raised, sheet: sheet ?? this.sheet);

  @override
  IdShadows lerp(IdShadows? other, double t) {
    if (other == null) return this;
    return IdShadows(
      card: BoxShadow.lerpList(card, other.card, t) ?? const [],
      raised: BoxShadow.lerpList(raised, other.raised, t) ?? const [],
      sheet: BoxShadow.lerpList(sheet, other.sheet, t) ?? const [],
    );
  }
}

/// Spacing scale (dp).
abstract final class IdSpace {
  /// Icon-to-text gap inside chips.
  static const double s1 = 4.0;
  /// Gap between related items; minimum gap between touch targets.
  static const double s2 = 8.0;
  /// Inside chips and list rows; gap between cards in a list.
  static const double s3 = 12.0;
  /// Screen side gutter and card padding.
  static const double s4 = 16.0;
  /// Padding of hero and promo cards.
  static const double s5 = 20.0;
  /// Space between sections on a screen.
  static const double s6 = 24.0;
  /// Space above a screen's first heading; empty-state padding.
  static const double s8 = 32.0;
  /// Large breaks, e.g. above the sign-in form.
  static const double s12 = 48.0;
}

/// Corner radii (dp).
abstract final class IdRadius {
  /// Small chips, thumbnails, admin buttons and inputs.
  static const double sm = 8.0;
  /// App buttons, inputs, OTP boxes, slot tiles.
  static const double md = 12.0;
  /// Cards: orders, addresses, items, promos.
  static const double lg = 16.0;
  /// Top corners of bottom sheets; hero cards.
  static const double xl = 24.0;
  /// Pills: steppers, status chips, the tab indicator, avatars.
  static const double full = 999.0;
}

/// Fixed component sizes (dp).
abstract final class IdSize {
  /// Minimum tappable area for any control, even when the visible icon is smaller.
  static const double touchTarget = 48.0;
  /// Primary and secondary buttons.
  static const double buttonHeight = 52.0;
  /// Text fields and the phone field.
  static const double inputHeight = 52.0;
  /// Top app bar height (plus the status-bar safe area).
  static const double appBar = 56.0;
  /// Bottom navigation height (plus the home-indicator safe area).
  static const double bottomNav = 64.0;
  /// Icons inside chips and captions.
  static const double iconSm = 16.0;
  /// Icons in buttons, list rows and fields.
  static const double iconMd = 20.0;
  /// App bar and bottom navigation icons.
  static const double iconLg = 24.0;
  /// Item and service thumbnails in lists.
  static const double thumb = 56.0;
}

/// Font families. The app loads them with google_fonts.
abstract final class IdFont {
  static const display = 'Outfit';
  static const body = 'Figtree';
  static const mono = 'Geist Mono';
  static const devanagari = 'Noto Sans Devanagari';
}

/// One type style from the design system: family, size, line height, weight and tracking.
@immutable
class IdTypeSpec {
  const IdTypeSpec(this.family, this.size, this.lineHeight, this.weight, this.letterSpacingEm);
  final String family;
  final double size;
  final double lineHeight;
  final FontWeight weight;
  final double letterSpacingEm;
}

/// Type scale. Use the TextStyles from `context.text` (theme.dart) rather than these directly.
abstract final class IdType {
  /// Totals and big numbers: the order total, the OTP digits.
  static const display = IdTypeSpec(IdFont.display, 32.0, 38.0, FontWeight.w700, -0.01);
  /// Large screen titles on top-level tabs and the first line of a hero card.
  static const headline = IdTypeSpec(IdFont.display, 24.0, 30.0, FontWeight.w700, -0.01);
  /// App bar titles and section headings.
  static const titleLg = IdTypeSpec(IdFont.display, 20.0, 26.0, FontWeight.w600, 0.0);
  /// Card titles, item names, list row labels.
  static const title = IdTypeSpec(IdFont.body, 17.0, 24.0, FontWeight.w600, 0.0);
  /// Input text and comfortable reading copy.
  static const bodyLg = IdTypeSpec(IdFont.body, 16.0, 24.0, FontWeight.w400, 0.0);
  /// Default body copy, addresses, descriptions.
  static const body = IdTypeSpec(IdFont.body, 15.0, 22.0, FontWeight.w400, 0.0);
  /// Button labels and tab labels.
  static const label = IdTypeSpec(IdFont.body, 15.0, 20.0, FontWeight.w600, 0.0);
  /// Chips, badges and field labels.
  static const labelSm = IdTypeSpec(IdFont.body, 13.0, 18.0, FontWeight.w600, 0.0);
  /// Helper text, timestamps, fine print. Never smaller than 12px.
  static const caption = IdTypeSpec(IdFont.body, 12.0, 16.0, FontWeight.w500, 0.0);
  /// Order numbers and promo codes.
  static const orderId = IdTypeSpec(IdFont.mono, 14.0, 20.0, FontWeight.w500, 0.0);
}
